#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.9.0
# Generated On: 28/07/2020 12:03
# Generated By: jleroux
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form = New-Object System.Windows.Forms.Form
$list_userlist = New-Object System.Windows.Forms.ComboBox
$l_etat = New-Object System.Windows.Forms.Label
$b_activer = New-Object System.Windows.Forms.Button
$b_desactiver = New-Object System.Windows.Forms.Button
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects
$userlist = Get-LocalUser


#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$b_activer_OnClick= 
{
#TODO: Place custom script here
    $selected = $list_userlist.SelectedItem
    Enable-LocalUser $selected
    if ((Get-LocalUser -name $selected).enabled -eq "True") {
        $l_etat.Text = "Etat : Activer"
    }
    else {$l_etat.Text = "Etat : Problème lors de l'activation"}
}

$b_desactiver_OnClick= 
{
#TODO: Place custom script here
    $selected = $list_userlist.SelectedItem
    disable-LocalUser $selected
    if ((Get-LocalUser -name $selected).enabled -eq "False") {
        $l_etat.Text = "Etat : Désactiver"
    }
    else {$l_etat.Text = "Etat : Problème lors de la désactivation"}
}

$handler_userList_Load= 
{
#TODO: Place custom script here

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 116
$System_Drawing_Size.Width = 292
$form.MaximizeBox = $False
$form.MinimizeBox = $False
$form.ClientSize = $System_Drawing_Size
$form.DataBindings.DefaultDataSourceUpdateMode = 0
$form.Name = "form"
$form.Text = "Activer/Desactiver Compte"
$form.add_Load($handler_userList_Load)
$form.Icon = [System.Drawing.Icon]::new("$PSScriptRoot\icon.ico")

$list_userlist.DataBindings.DefaultDataSourceUpdateMode = 0
$list_userlist.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 28
$System_Drawing_Point.Y = 13
$list_userlist.Location = $System_Drawing_Point
$list_userlist.Name = "list_userlist"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 226
$list_userlist.Size = $System_Drawing_Size
$list_userlist.TabIndex = 4

$form.Controls.Add($list_userlist)

$l_etat.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 28
$System_Drawing_Point.Y = 84
$l_etat.Location = $System_Drawing_Point
$l_etat.Name = "l_etat"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 236
$l_etat.Size = $System_Drawing_Size
$l_etat.TabIndex = 3
$l_etat.Text = "Etat : "

$form.Controls.Add($l_etat)


$b_activer.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 147
$System_Drawing_Point.Y = 52
$b_activer.Location = $System_Drawing_Point
$b_activer.Name = "b_activer"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 107
$b_activer.Size = $System_Drawing_Size
$b_activer.TabIndex = 2
$b_activer.Text = "Activer"
$b_activer.UseVisualStyleBackColor = $True
$b_activer.add_Click($b_activer_OnClick)

$form.Controls.Add($b_activer)


$b_desactiver.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 28
$System_Drawing_Point.Y = 52
$b_desactiver.Location = $System_Drawing_Point
$b_desactiver.Name = "b_desactiver"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 107
$b_desactiver.Size = $System_Drawing_Size
$b_desactiver.TabIndex = 1
$b_desactiver.Text = "Désactiver"
$b_desactiver.UseVisualStyleBackColor = $True
$b_desactiver.add_Click($b_desactiver_OnClick)


#Remplir la liste
foreach ($elem in $userlist){
    $list_userlist.Items.Add($elem)
}
$form.Controls.Add($b_desactiver)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form.WindowState
#Init the OnLoad event to correct the initial state of the form
$form.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
